[server]
fileWatcherType = "none"

[global]
suppressDeprecationWarnings = true

[theme]
primaryColor = "#6C63FF"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#1A1D2E"
textColor = "#FAFAFA"
font = "sans serif"
